version: "3.8"

services:
  database:
    image: scylladb/scylla:5.4
    container_name: database
    volumes:
      - "./lib/scylla:/var/lib/scylla"
      - "./lib/mutant-data.txt:/mutant-data.txt"
    ports:
      - 9042:9042
